logging:
  level:
     root: info
     org:
       springframework: info
       hibernate: info
       eclipse: info
       apache: info
  file: "logs/arrow.log"

arrow:
  bowIp: 127.0.0.1
  bowPort: 9998
  username: aaa
  password: bbb
  devices:
  - id: 1
  - id: 3
