logging:
  level:
     root: info
     org:
       springframework: info
       hibernate: info
       eclipse: info
       apache: info
  file: "logs/arrow.log"

arrow:
  bowIp: 35.165.220.128
  bowPort: 9998
  username: aaa
  password: bbb
  devices:
  - id: 2