##config
localIp: 0.0.0.0
tcpPort: 9998
httpPort: 82
httpsPort: 443
startPort: 1024
endPort: 65535
domain: www.kisme.org
users:
- id: 1
  username: aaa
  password: bbb
  devices:
  - id: 1
    mapIp: 10.50.115.18
    mapPort: 22
    remoteIp: 127.0.0.1
    remotePort: 9001
    protocolType: TCP
  - id: 2
    mapIp: 192.168.56.101
    mapPort: 22
    remoteIp: 127.0.0.1
    remotePort: 9002
    protocolType: TCP
  - id: 3
    mapIp: 192.168.234.63
    mapPort: 42080
    remoteIp: 127.0.0.1
    remotePort: 9003
    subDomain: local
    protocolType: HTTP
- id: 1
  username: ccc
  password: ddd
  devices:
  - id: 1
    mapIp: 10.50.115.18
    mapPort: 22
    remoteIp: 127.0.0.1
    remotePort: 9004
    protocolType: TCP
