users:
- id: 1
  username: aaa
  password: bbb
  devices:
  - id: 1
    mapIp: 10.50.115.18
    mapPort: 22
    remoteIp: 127.0.0.1
    remotePort: 1024
    protocolType: TCP
  - id: 2
    mapIp: 192.168.56.101
    mapPort: 22
    remoteIp: 127.0.0.1
    remotePort: 1025
    protocolType: TCP
  - id: 3
    mapIp: 127.0.0.1
    mapPort: 3030
    remoteIp: 127.0.0.1
    remotePort: 1025
    subDomain: local
    protocolType: HTTP
