###jetty
server:
   port: 3030
   contextPath: /bow

spring:
  thymeleaf:
    enabled: true
    cache: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
  output:
    ansi:
      enabled: detect